{
 "title": "Asus RT-AC1900P",
 "description": "Router Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "WAN In",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  internetRXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 5G Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wireless5gTXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "LAN Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wiredTXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 2.4G Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wireless2gTXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WAN Out",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  internetTXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 5G In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wireless5gRXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "LAN In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wiredRXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 2.4G In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wireless2gRXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  cpu1Percentage\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    },
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  cpu2Percentage\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  coretempCPU\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    },
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  coretemp5g\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    },
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  coretemp2g\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WAN In",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  internetRXSpeed\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/250 MB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  ramUsage\nFROM allStatus\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  }
 ]
}